name: starship-bcarnazzi
version: "1.21.1"
summary: The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
  - it's fast – really really fast! 🚀
  - configure every aspect of your prompt.
  - works on any shell, on any operating system.
  - shows relevant information at a glance.
  - support for all your favorite tools.
  – start using it in minutes.
license: ISC
base: core22
confinement: classic
grade: stable

apps:
  starship:
    command: bin/starship

parts:
  starship:
    plugin: rust
    source: https://github.com/starship/starship.git
    source-tag: v1.21.1
    build-packages:
      - cmake
    build-attributes:
      - enable-patchelf
